# Generated by Django 5.1.4 on 2025-02-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_embarque_maritimo',
            field=models.CharField(blank=True, db_column='Data_Embarque_Maritimo', max_length=50, null=True, verbose_name='Data de Embarque Marítimo'),
        ),
    ]
