# Generated by Django 5.1.2 on 2025-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_alter_equipamento_bl_alter_equipamento_ccid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status_js',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status JS'),
        ),
    ]
