# Generated by Django 5.2.3 on 2025-06-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_equipamento_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_viagem',
        ),
    ]
