# Generated by Django 5.2.3 on 2025-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_remove_equipamento_sla_viagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_envio_brasil',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_insercao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_maritimo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_operacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_retirada',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='sla_terrestre',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status_operacao',
            field=models.CharField(blank=True, choices=[('em_viagem', 'Em Viagem'), ('no_destino', 'No Destino'), ('desacoplado', 'Desacoplado'), ('em_estoque', 'Em Estoque'), ('na_fazenda', 'Na Fazenda')], default='em_viagem', max_length=20, null=True, verbose_name='Status da Operação'),
        ),
    ]
