# Generated by Django 5.2.3 on 2025-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_remove_equipamento_sla_envio_brasil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='lacre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lacre'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='lacre_inn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lacre INN'),
        ),
    ]
