[uwsgi]
chdir           = /var/www/controller
module          = app.wsgi:application
home            = /var/www/controller/venv

master          = true
processes       = 10

socket          = /var/www/controller/controller.sock
chmod-socket    = 660
chown-socket    = www-data:www-data

vacuum          = true
;plugin        = python3    ← opcional/remova se não precisar
