# Generated by Django 5.2.3 on 2025-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=100)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('tratado_em', models.DateTimeField(auto_now_add=True)),
                ('tratado_por', models.CharField(default='Sistema', max_length=100)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['guid', 'tipo_evento'], name='core_evento_guid_41b4a7_idx'), models.Index(fields=['tratado_em'], name='core_evento_tratado_6e83f1_idx')],
                'unique_together': {('guid', 'tipo_evento', 'valor')},
            },
        ),
    ]
