# Generated by Django 5.2.3 on 2025-07-03 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventotratado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventotratado',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveIndex(
            model_name='eventotratado',
            name='core_evento_guid_41b4a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventotratado',
            name='core_evento_tratado_6e83f1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventotratado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='data_tratamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='fonte',
            field=models.CharField(blank=True, choices=[('T42', 'T42'), ('AssetsControls', 'AssetsControls')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='geofence',
            field=models.CharField(blank=True, help_text='Nome da geofence', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='id_equipamento',
            field=models.CharField(blank=True, help_text='ID do equipamento (preenchido automaticamente)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='nome_equipamento',
            field=models.CharField(blank=True, help_text='Nome do equipamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre o tratamento'),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('tratado', 'Tratado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='timestamp_evento',
            field=models.BigIntegerField(blank=True, help_text='Timestamp do evento', null=True),
        ),
        migrations.AlterField(
            model_name='eventotratado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventotratado',
            name='tipo_evento',
            field=models.CharField(choices=[('aberta', 'Porta Aberta'), ('fechada', 'Porta Fechada'), ('luz', 'Alerta de Luminosidade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventotratado',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor (ex: luminosidade)', max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='eventotratado',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='eventotratado',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='eventotratado',
            name='tratado_em',
        ),
        migrations.RemoveField(
            model_name='eventotratado',
            name='tratado_por',
        ),
    ]
