# Generated by Django 5.2.3 on 2025-07-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventotratado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotratado',
            name='valor',
            field=models.CharField(blank=True, help_text='Valor (ex: luminosidade)', max_length=100, null=True),
        ),
    ]
