# Generated by Django 5.2.3 on 2025-07-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_eventotratado_nome_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventotratado',
            name='origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='tratado',
            field=models.BooleanField(default=False),
        ),
    ]
