# Generated by Django 5.2.3 on 2025-07-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventotratado_origem_eventotratado_tratado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoTratado',
        ),
    ]
