# Generated by Django 5.2.3 on 2025-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_eventotratado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=20)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
