# Generated by Django 5.2.3 on 2025-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventotratado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventotratado',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RenameField(
            model_name='eventotratado',
            old_name='timestamp',
            new_name='criado_em',
        ),
        migrations.AddIndex(
            model_name='eventotratado',
            index=models.Index(fields=['criado_em'], name='core_evento_criado__8c4e99_idx'),
        ),
    ]
