# Generated by Django 5.2.3 on 2025-07-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_eventotratado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventotratado',
            name='alerta_disparado',
            field=models.BooleanField(default=False),
        ),
    ]
