# Generated by Django 5.2.3 on 2025-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_eventotratado_acao_tomada_eventotratado_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altocafezalmodel',
            options={'permissions': [('can_access_mapa', 'Pode acessar o mapa')], 'verbose_name': 'Alto Cafezal', 'verbose_name_plural': 'Alto Cafezal'},
        ),
        migrations.AlterModelOptions(
            name='eventotratado',
            options={'ordering': ['-criado_em'], 'permissions': [('can_access_eventos', 'Pode acessar eventos')]},
        ),
        migrations.AddField(
            model_name='eventotratado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('tratado', 'Tratado'), ('ignorado', 'Ignorado')], default='pendente', max_length=20),
        ),
    ]
