# Generated by Django 5.2.3 on 2025-10-14 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_altocafezalmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaGeofencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=255)),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('tipo_alerta', models.CharField(choices=[('saida_fazenda', 'Saída de Fazenda'), ('parado_porto', 'Parado no Porto')], max_length=50)),
                ('nome_local', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('saiu_em', models.DateTimeField(blank=True, null=True)),
                ('parado_desde', models.DateTimeField(blank=True, null=True)),
                ('dias_parado', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alerta_disparado', models.BooleanField(default=False)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('tratado', 'Tratado'), ('ignorado', 'Ignorado')], default='pendente', max_length=20)),
                ('tratado_em', models.DateTimeField(blank=True, null=True)),
                ('tratado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Geofencing',
                'verbose_name_plural': 'Alertas de Geofencing',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['guid', '-criado_em'], name='core_alerta_guid_6abaf9_idx'), models.Index(fields=['tipo_alerta', 'status'], name='core_alerta_tipo_al_b60689_idx'), models.Index(fields=['resolvido'], name='core_alerta_resolvi_7cfb3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PosicaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=255)),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dentro_de_cerca', models.BooleanField(default=False)),
                ('nome_cerca', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_cerca', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidade', models.FloatField(blank=True, null=True)),
                ('parado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Posição de Equipamento',
                'verbose_name_plural': 'Posições de Equipamentos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['guid', '-timestamp'], name='core_posica_guid_3dad73_idx'), models.Index(fields=['dentro_de_cerca', 'tipo_cerca'], name='core_posica_dentro__a5578b_idx')],
            },
        ),
    ]
