# Generated by Django 5.2.3 on 2025-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_equipamento_delete_codigoescaneado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
