# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_equipamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='medidas_caixa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ] 