# Generated by Django 5.2.3 on 2025-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_add_peso_medidas_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.CharField(choices=[('guardian', 'Guardian'), ('sensor_porta', 'Sensor de Porta'), ('tetis', 'Tetis')], default='tetis', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
