# Generated by Django 5.2.3 on 2025-07-16 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_equipamento_tipo_equipamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['-data_recebido'], 'permissions': [('can_access_scanner', 'Pode acessar o scanner'), ('can_access_eventos', 'Pode acessar eventos')], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='usuario_cadastro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
